[package]
name         = "lebron-core"
rust-version = "1.88"
version      = "0.1.0"
edition      = "2024"

[dependencies]
embedded-graphics = "0.8.1"
fastrand = { version = "2.3.0", default-features = false }
tinytga = "0.5"
